### ISSUE TITLE
Error while running test datset

### ISSUE THREAD

**Issue by ShriramHPatel** [ASaiM/group_humann2_uniref_abundances_to_GO#2]
I have used Humann2 for functional profiling using uniref50 datbase.
After that I wanted to map it to corresponding Go. So i install this scripts following each and every step  mentioned here. However, test run gave me an error. Full error and commands I run is as follow:

`qiime@qiime-190-virtual-box:~/Desktop/group_humann2_uniref_abundances_to_GO/test-data$ ../group_humann2_uniref_abundances_to_GO.sh -i humann2_gene_families.csv -m moleculat.txt -b biological.txt -c cellular.txt -a go_02_22_2016.obo -s goslim_metagenomics_02_22_2016.obo -u map_infogo1000_uniref50_02_22_2016.txt
# Format HUMAnN2 UniRef50 GO mapping
# Map to slim GO

load obo file go_02_22_2016.obo
46135 nodes imported
load obo file goslim_metagenomics_02_22_2016.obo
163 nodes imported
# Format slim GO
# Regroup UniRef50 to GO

Loading table from: humann2_gene_families.csv
Loading custom groups file: tmp_data/uniref_go_mapping_output.txt
Loading mapping file from: tmp_data/uniref_go_mapping_output.txt
Original Feature Count: 262358; Grouped 1+ times: 22224 (%8.5); Grouped 2+ times: 17341 (%6.6)
# Regroup GO to slim GO

Loading table from: tmp_data/humann2_go_abundances.txt
Loading custom groups file: tmp_data/formatted_humman2_go_slim.txt
Loading mapping file from: tmp_data/formatted_humman2_go_slim.txt
Original Feature Count: 820; Grouped 1+ times: 817 (%99.6); Grouped 2+ times: 145 (%17.7)
# Format slim GO abundance

**Traceback (most recent call last):
  File "../src/format_humann2_output.py", line 90, in <module>
    format_humann2_output(args, go_annotations)
  File "../src/format_humann2_output.py", line 66, in format_humann2_output
    namespace = go_annotations[go_id]["namespace"]
KeyError: 'UNGROUPED**'```

Please help me with this..

Thanks

**Comment by bebatut** [comment]
Hi,

Normally it is fixed with #3 

Thanks for spotting the error.

Bérénice

**Comment by ShriramHPatel** [comment]
Hi,
Worked perfectly now.

Thanks for the early solution

Best
